name: renovate

on:
  push:
  schedule:
    #    - cron: '5 */6 * * *'
    - cron: '*/30 * * * *'

  workflow_dispatch:

  
env:
  # RENOVATE_DRY_RUN: ${{ ((github.event_name != 'schedule' && github.event_name != 'workflow_dispatch') || (github.ref_name != 'main') && 'full' || '' }}
  RENOVATE_DRY_RUN: ${{ ((github.event_name != 'schedule' && github.event_name != 'workflow_dispatch')) && 'full' || '' }} # dry-run on main to eleminate race condition
  # RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG }}

jobs:
  gitlab:
    runs-on: ubuntu-24.04
  
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Restore renovate repo cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            /tmp/renovate/cache/renovate/repository
          key: repo-cache-${{ github.run_id }}
          restore-keys: |
            repo-cache-

      - name: Restore renovate package cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            /tmp/renovate/cache/renovate/renovate-cache-sqlite
          key: package-cache-${{ github.run_id }}
          restore-keys: |
            package-cache-

      - name: Restore perms
        run: |
          if [ -d /tmp/renovate ]; then
            echo "fixing renovate perms"
            sudo chown -R 12021:0 /tmp/renovate/
          fi

      - name: Renovate
        uses: renovatebot/github-action@248bf5a619694187930adc80b9343c37761c173f # v43.0.1
        with:
          token: ${{ secrets.GITLAB_TOKEN }}
          renovate-version: 40.62.1
          configurationFile: config.js
          docker-volumes: |
            /tmp:/tmp ;
            ${{ github.workspace }}:/github-action
        env:
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: gitlab
          RENOVATE_REPOSITORY_CACHE: 'enabled'
          RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>

          RENOVATE_X_SQLITE_PACKAGE_CACHE: true

      - name: Save renovate repo cache
        if: always() && env.RENOVATE_DRY_RUN != 'full'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            /tmp/renovate/cache/renovate/repository
          key: repo-cache-${{ github.run_id }}

      - name: Save renovate package cache
        if: always() && env.RENOVATE_DRY_RUN != 'full'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            /tmp/renovate/cache/renovate/renovate-cache-sqlite
          key: package-cache-${{ github.run_id }}
